from typing import Annotated
from fastapi import Depends
from utils import get_current_user, get_current_admin
from sqlalchemy.orm import Session
from db.database import SessionLocal


"""
    get_db is used in dependencies and it is located here
    so new sessions are not generated by mistake
    and to avoid circular imports
"""


def get_db() -> Session:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


db_dependency = Annotated[Session, Depends(get_db)]

admin_dependency = Annotated[dict, Depends(get_current_admin)]

user_dependency = Annotated[dict, Depends(get_current_user)]

